# Generated by Django 3.1.1 on 2020-10-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201001_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
