# Generated by Django 3.1.1 on 2020-10-03 02:43

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('core', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='verification_document',
            field=models.FileField(null=True, upload_to='doctors/verification/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Places willing to work'),
        ),
    ]
