# Generated by Django 3.1.1 on 2020-10-11 09:05

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('core', '0005_auto_20201003_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='reference_file_1',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reference_file_2',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='reference_file_3',
            field=models.FileField(null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=255)),
                ('report_by', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('prescriptions', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
    ]
