# Generated by Django 3.1.1 on 2020-10-13 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201011_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
