# Generated by Django 3.1.1 on 2020-10-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='tags',
        ),
        migrations.AddField(
            model_name='doctor',
            name='tags',
            field=models.CharField(default='Damak', max_length=500),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='report',
            name='prescriptions',
        ),
        migrations.AddField(
            model_name='report',
            name='prescriptions',
            field=models.CharField(default='Paracetamol', max_length=500),
            preserve_default=False,
        ),
    ]
