# Generated by Django 3.1.1 on 2020-10-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201013_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='inquiry_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.person'),
        ),
    ]
