# Generated by Django 3.1.1 on 2020-10-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201015_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='patient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
