# Generated by Django 3.1.1 on 2020-10-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201015_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AddField(
            model_name='inquiry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
